# This file was *autogenerated* from the file figs_MetMatBio.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_4 = Integer(4)
plst = []

############ Rysunek 1
p  = plot(sin(x),(x,_sage_const_1 ,_sage_const_11 ),figsize=_sage_const_4 )
plst.append( [p,"moj_sinus"] ) 
####################

############ Rysunek 2 plik 
p  = plot(sin(_sage_const_2 *x+x**_sage_const_2 ),(x,_sage_const_1 ,_sage_const_11 ),figsize=_sage_const_4 )
plst.append( [p,"inny_sinus"] ) 
####################


for p,n in plst:
    p.save('%s.png'%n)
    p.save('%s.svg'%n)
    p.save('%s.pdf'%n)
