# This file was *autogenerated* from the file rysunki_algebra.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_13 = Integer(13); _sage_const_4p4 = RealNumber('4.4'); _sage_const_3p85 = RealNumber('3.85'); _sage_const_15 = Integer(15); _sage_const_0p6 = RealNumber('0.6'); _sage_const_3p15 = RealNumber('3.15'); _sage_const_3p05 = RealNumber('3.05'); _sage_const_2p65 = RealNumber('2.65')
plst = []

############ Rysunek 1
var('x1,x2')

eq1 = _sage_const_2 *x1-x2==_sage_const_1 ; eq2 = x1+x2==_sage_const_5 

p1 = implicit_plot(eq1, (x1, _sage_const_0 , _sage_const_5 ), (x2, _sage_const_0 , _sage_const_5 ), color='red')
p2 = implicit_plot(eq2, (x1, _sage_const_0 , _sage_const_5 ), (x2, _sage_const_0 , _sage_const_5 ), color='green')
P0 = point((_sage_const_2 ,_sage_const_3 ), color='black',size=_sage_const_15 , zorder=_sage_const_5 , aspect_ratio=_sage_const_1 , figsize=_sage_const_5 )

txt0 = text('$P(2,3)$', (_sage_const_2p65 , _sage_const_3p05 ), color='black', fontsize=_sage_const_13 )
txt1 = text('$2x_1-\,x_2=\,1$', (_sage_const_3p85 , _sage_const_4p4 ), color='black', fontsize=_sage_const_13 )
txt2 = text('$x_1+\,x_2=\,5$', (_sage_const_3p15 , _sage_const_0p6 ), color='black', fontsize=_sage_const_13 )

p  = P0+p1+p2+txt0+txt1+txt2
plst.append( [p,"uklad_rownan"] ) 
####################

for p,n in plst:
    p.save('%s.png'%n)
    p.save('%s.svg'%n)
    p.save('%s.pdf'%n)
