# This file was *autogenerated* from the file make_figs.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_4p0 = RealNumber('4.0'); _sage_const_1p5 = RealNumber('1.5'); _sage_const_1p05 = RealNumber('1.05'); _sage_const_0p5 = RealNumber('0.5'); _sage_const_0p4 = RealNumber('0.4'); _sage_const_3p2 = RealNumber('3.2'); _sage_const_0p05 = RealNumber('0.05'); _sage_const_25 = Integer(25)
def get_fig(x = _sage_const_0p4 ,a=_sage_const_0p5 ):
       pkts = []
       for i in range(_sage_const_25 ):
           pkts.append( (i,x) )
           x = a*x*(_sage_const_1 -x)


       p=line(pkts,figsize=(_sage_const_4 ,_sage_const_2 ),ymin=-_sage_const_0p05 ,ymax=_sage_const_1p05 ,\
        #ticks=[2,None],\
         axes_labels=[r"$i$",r"$x_i$"],\
         #tick_formatter="latex",\
         thickness=_sage_const_0p5 ,\
         marker='o',
         markerfacecolor='red'    )
       return p
a_lst = [_sage_const_0p5 ,_sage_const_1p5 ,_sage_const_3p2 ,_sage_const_4p0 ]
for i,a_ in enumerate(a_lst):
    get_fig(x = _sage_const_0p4 ,a=a_).save("xi%d.pdf"%i)

